version: '3.8'
services:
  app:
    image: armasnevolainen/study_shelf:latest_v1
    environment:
      - DISPLAY=host.docker.internal:0
      - DB_URL=jdbc:mariadb://db:3306/StudyShelf
      - DB_USER=appuser
      - DB_PASSWORD=password
    volumes:
      - ./src/main/resources/credentials:/app/credentials
      - ${DOWNLOADS_DIR:-~/Downloads}:/app/downloads
    depends_on:
      - db

  db:
    image: mariadb:latest
    environment:
      - MARIADB_DATABASE=StudyShelf
      - MARIADB_USER=appuser
      - MARIADB_PASSWORD=${DB_PASSWORD}
      - MARIADB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    volumes:
      - mariadb-data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  mariadb-data: